<form action="<?php echo Mage::getUrl('massstock/test/consumer') ?>" method="post">
    <label>Consumer Key</label>
    <br />
    <input type="text" name="consumer_key" />
    <br />
    
    <label>Consumer Secret</label>
    <br />
    <input type="text" name="consumer_secret" />
    <br />
    
    <br />
    <button type="submit" title="Submit" class="button">
        <span><span>Submit</span></span>
    </button>
</form>