<?php
	/** @var Mage_CatalogInventory_Model_Resource_Stock_Item_Collection $items */
	$items = Mage::getResourceModel('cataloginventory/stock_item_collection');
	$items->setPageSize(100)->setCurPage(1);
	
	$serializableItems = [];
	foreach ($items as $item) {
		$serializableItems[] = [
			'item_id' => $item->getId(),
			'qty' => $item->getQty()
		];
	}

	$exampleRequests = [
		'1 Item by Product ID' => [ 
			[
				'product_id' => $item->getProductId(),
				'stock_id' => $item->getStockId(),
				'qty' => $item->getQty()
			]
		],
		'1 Item by Item ID' => [
			[
				'item_id' => $item->getId(),
				'qty' => $item->getQty()
			]
		],
		'100 Items' => $serializableItems
	];
?>

<div class="content-row">
	<div class="content-column content-column--1">
		<form id="request_form" action="<?php echo Mage::getUrl('massstock/test/callAjax') ?>" method="post">
			<label>Content Type</label>
			<br />
			<select name="content_type">
				<option value="text/csv">CSV</option>
				<option value="application/json">JSON</option>
			</select>
			<br />
			<br />
			
			<label>Example Request</label>
			<br />
			<?php foreach ($exampleRequests as $label => $request): ?>
				<button data-request-button="<?php echo $label ?>" class="button">
					<span><span><?php echo $label ?></span></span>
				</button>
			<?php endforeach; ?>
			<br />
			<br />
			
			<label>Request Content</label>
			<br />
			<textarea name="request_content"></textarea>
			<br />
			
			<br />
			<button class="button" id="submit_buton">
				<span><span>Submit</span></span>
			</button>
		</form>
	</div>
	<div class="content-column content-column--2">
		<h2>Responses</h2>
		<ul class="response-list">
		</ul>
	</div>
</div>

<style>
	[name=request_content] {
		min-width: 100%;
		min-height: 300px;
		font-family: monospace;
	}
	
	.content-row {
		margin-right: -15px;
	}
	
	.content-row:after {
		clear: both;
	}
	
	.content-column {
		float: left;
		padding-right: 15px;
	}
	
	.content-column--1 {
		width: 40%;
	}
	
	.content-column--2 {
		width: 60%;
	}
	
	.response-list {
		width: 100%;
		height: 500px;
		overflow: scroll;
		border: 1px solid black;
	}
	
	.response {
		margin: 5px;
		border: 1px solid gray;
		opacity: 0;
		transition: opacity 0.5s;
	}
	
	.response--success .response__title {
		background: #8f8;
	}
	
	.response--error .response__title {
		background: #f88;
	}
	
	.response__title {
		padding: 5px;
		border-bottom: 1px solid gray;
	}
	
	.response__content {
		padding: 5px;
		overflow-x: auto;
	}
	
	.response__content pre {
		white-space: pre;
		word-break: normal;
		word-wrap: normal;
	}
</style>

<script>
	(function ($) {
		var requests = <?php echo json_encode($exampleRequests) ?>;
		
		var encoders = {
			'text/csv': function (data) {
				var headersMap = {};
				data.forEach(function (item) {
					for (var key in item) {
						headersMap[key] = true;
					}
				});
				var headers = [];
				for (var header in headersMap) {
					headers.push(header);
				}
				
				var lines = [];
				lines.push(headers.join(';'));
				
				data.forEach(function (item) {
					lines.push(
						headers
							.map(function (header) {
								return item[header] || '';
							})
							.join(';')
					);
				});
				
				return lines.join('\n');
			},
			'application/json': function (data) {
				return JSON.stringify(data, null, 4);
			}
		};
	
		$('[data-request-button]').on('click', function (e) {
			e.preventDefault();
			
			var request = requests[$(this).attr('data-request-button')];
			var selectedContentType = $('[name=content_type]').val();
			
			$('[name=request_content]').val(encoders[selectedContentType](request));
		});
		
		var addResponse = function (title, cssClass, content) {
			var responseTitle = $('<div>');
			responseTitle.addClass('response__title').text(title);
		
			var responseContent = $('<pre>');
			responseContent.addClass('response__content').html(content);
			
			var newItem = $('<li>')
				.addClass('response')
				.addClass(cssClass)
				.append(responseTitle)
				.append(responseContent);
				
			$('.response-list').prepend(newItem);
			
			setTimeout(function () { newItem.css('opacity', 1) }, 0);
		};
		
		var hasRestError = function (response) {
			 if (response.response.messages && response.response.messages.error) {
			 	return true;
			 }
			 
			 if (response.response.error) {
			 	return true;
			 }
			 
			 return false;
		}
		
		$('#submit_buton').on('click', function (e) {
			e.preventDefault();
			$.ajax({
				'url': $('#request_form').attr('action'),
				'data': $('#request_form').serialize(),
				'method': $('#request_form').attr('method'),
				'dataType': 'json'
			}).done(function (response) {
				if (response.error) {
					return addResponse('AJAX error', 'response--error', response.error);
				}

				if (hasRestError(response)) {
					return addResponse('REST call error', 'response--error', JSON.stringify(response.response, null, 4));
				}
				
				addResponse('Success', 'response--success', JSON.stringify(response.response, null, 4));
			}).fail(function (error) {
				addResponse('Server error', 'response--error', error.responseText);
			});
		});
	})(jQuery);
</script>