<?php
/** @var Barcala_MassstockTest_Block_Form $this */
?>

<div class="content-row">
    <div class="content-column content-column--1">
        <form id="request_form" action="<?php echo $this->getPostUrl() ?>" method="post">
            <label>Content Type</label>
            <br />
            <select name="content_type">
                <option value="text/csv">CSV</option>
                <option value="application/json">JSON</option>
            </select>
            <br />
            <br />
            
            <label>Example Request</label>
            <br />
            <ul class="example-requests">
                <?php foreach ($this->getExampleRequests() as $label => $request): ?>
                <li>
                    <button data-request-button="<?php echo $label ?>" class="button">
                        <span><span><?php echo $label ?></span></span>
                    </button>
                </li>
                <?php endforeach; ?>
            </ul>
            
            <label>Request Content</label>
            <br />
            <textarea name="request_content"></textarea>
            <br />
            
            <br />
            <button class="button" id="submit_buton">
                <span><span>Submit</span></span>
            </button>
        </form>
    </div>
    <div class="content-column content-column--2">
        <h2>Responses</h2>
        <ul class="response-list">
        </ul>
    </div>
</div>

<script type="application/json" id="example-requests">
    <?php echo json_encode($this->getExampleRequests()) ?>
</script>